name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    uses: <org>/bookloop-platform/.github/workflows/backend-java.yml@v1
    with:
      image_name: <org>/<servico>-backend
      java_version: "21"
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
